apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookshelf-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
    spec:
      containers:
      - name: bookshelf-node
        # Replace fleet-space-404401 with your own project ID
        image: gcr.io/fleet-space-404401/bookshelf-node:v1
        # Bookshelf listens on port 8080 for web traffic.
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: fleet-space-404401
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3